In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
emails=pd.read_csv('Emails.csv')
emails.head()

text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [21]:
from sklearn.feature_extraction.text import CountVectorizer

In [23]:
cv=CountVectorizer()
X=cv.fit_transform(emails['text'])

In [26]:
y=emails['spam']

In [27]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score  
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LogisticRegression

In [29]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [30]:
log_reg=LogisticRegression()
log_reg.fit(X_train,y_train)
y_pred=log_reg.predict(X_test)


In [ ]:
log_reg_score=accuracy_score(y_test,y_pred)
log_reg_score

0.9841353781068218

In [35]:
nb_classifier=MultinomialNB()
nb_classifier.fit(X_train,y_train)
y_pred=nb_classifier.predict(X_test)

In [36]:
nb_classifier_score=accuracy_score(y_test,y_pred)
nb_classifier_score

0.9883659439450027

In [38]:
test_email=["Hi, I am interested in your product. Please send me more information."]
test_email=cv.transform(test_email)
log_reg.predict(test_email)

array([0])

In [39]:
test_email=["Hi, I am interested in your product. Please send me more information."]
test_email=cv.transform(test_email)
nb_classifier.predict(test_email)

array([0])

In [42]:
test_email=X_test[0]
log_reg.predict(test_email)

array([0])

In [43]:
test_email=X_test[0]
nb_classifier.predict(test_email)

array([0])

In [52]:
y_test[y_test==1]

561     1
177     1
1109    1
401     1
1033    1
       ..
314     1
113     1
960     1
1114    1
684     1
Name: spam, Length: 493, dtype: int64

In [54]:
test_email=X_test[561]
log_reg.predict(test_email)

array([1])

In [55]:
nb_classifier.predict(test_email)

array([1])